sudo: required
services:
    - docker

before_install:
    - docker build -t ssalihu/docker-react -f Dockerfile.dev . 
   
script:
    - docker run -e CI=true ssalihu/docker-react npm run test -- --coverage

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DokcerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-957826690966"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY     
    secret_access_key: $AWS_SECRET_KEY